server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${DOMAIN:http://localhost}
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false

