server:
  port: ${PORT:8761}


eureka:
  instance:
    hostname: localhost
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0


